# Generated by Django 3.0.3 on 2020-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_remove_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
